services:
  db:
    image: postgres:13
    restart: always
    volumes:
      - website-up-date_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: shiraji_website_1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toolbandima198607050@

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000 construction_site.wsgi:application
    volumes:
      - .:/app
    ports:
      - "80:8000"
    env_file:
      - .env
    depends_on:
      - db

volumes:
  website-up-date_postgres_data:
    external: true