services:
  db:
    image: postgres:13
    restart: always
    volumes:
      - website-up-date_postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: shiraji_website_1
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: toolbandima198607050@

  web:
    build: .
    command: gunicorn --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "80:8000"
    env_file:
      - .env
    depends_on:
      - db


  # nginx:
  #   image: nginx:alpine
  #   restart: always
  #   volumes:
  #     - ./nginx.conf:/etc/nginx/nginx.conf:ro
  #     - ./staticfiles:/app/staticfiles:ro
  #     - ./media:/app/media:ro
  #   ports:
  #     - "80:80"
  #   depends_on:
  #     - web

volumes:
  website-up-date_postgres_data:
    external: trueroot@shiraji:~/shiraji2# 